---
object_type: method
version: 1.0
object:
  attributes:
    name: vcenter_reconfig_vm_memory_hotadd
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
  inputs: []
