---
object_type: method
version: 1.0
object:
  attributes:
    name: scan_guest_for_file_via_ssa
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
  inputs: []
