---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
  fields:
  - playbook_directory:
      value: "/etc/ansible/plays/ansible-ad-join"
  - inventory_directory:
      value: "/etc/ansible/plays/ansible-ad-join/cloudforms_inventory"
