---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
  fields:
  - servername:
      value: rigc1.gtk.gtech.com
  - username:
      value: opswareservice
  - password:
      value: v2:{PAcceR/uPbRwmt0C1DDo7A==}
  - basedn:
      value: dc=gtk,dc=gtech,dc=com
  - port:
      value: '389'
