---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - EmailOwner:
      value: "/Service/Retirement/Email/service_retirement_emails"
  - DeleteServiceFromVMDB:
      value: "#"
