---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: vcenter_reconfig_vm_hotadd
    inherits: 
    description: 
  fields:
  - Step1:
      value: "/Integration/VMware/vCenter/Methods/vcenter_check_powered_off"
  - Step2:
      value: "/Integration/VMware/vCenter/Methods/vcenter_reconfig_vm_cpu_hotadd"
  - Step3:
      value: "/Integration/VMware/vCenter/Methods/vcenter_reconfig_vm_cpu_hotadd_check"
  - Step4:
      value: "/Integration/VMware/vCenter/Methods/vcenter_reconfig_vm_memory_hotadd"
  - step5:
      value: "/Integration/VMware/vCenter/Methods/vcenter_reconfig_vm_memory_hotadd_check"
