---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: vcenter_reconfig_vm_guestid
    inherits: 
    description: 
  fields:
  - Step3:
      value: "/Integration/VMware/vCenter/Methods/vcenter_reconfig_vm_guestid"
  - Step4:
      value: "/Integration/VMware/vCenter/Methods/vcenter_reconfig_vm_guestid_check"
