---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: scan_guest_for_file_via_ssa
    inherits: 
    description: 
  fields:
  - method1:
      value: scan_guest_for_file_via_ssa
