---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: vcenter_reconfig_vm_guestid_check
    inherits: 
    description: 
  fields:
  - method1:
      value: vcenter_reconfig_vm_guestid_check
