---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: vcenter_reconfig_vm_guestid
    inherits: 
    description: 
  fields:
  - rel2:
      value: "/Integration/VMware/vCenter/StateMachines/vcenter_reconfig_vm_guestid"
