---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: generate_mac_address
    inherits: 
    description: 
  fields:
  - vmware_meth1:
      value: vmware_generate_mac_address
  - redhat_meth1:
      value: redhat_generate_mac_address
